server.port=3000

spring.h2.console.enabled=true
spring.h2.console.lpath=/h2-console

spring.datasource.url=jdbc:h2:{caminho-do-banco}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
